// @hanzo/ui — the one Hanzo component library, on @hanzo/gui + @hanzo/design.
//
// ONE substrate: every component renders through @hanzo/gui primitives, so the
// same import works on web, native (expo) and desktop (Tauri). The ROOT barrel is
// the canonical component API apps import; the product layer and the design
// tokens are their own subpaths, so importing a Button never drags in a chart.
//
//   import { Button, Card, Dialog, DropdownMenu, Input, Toaster } from '@hanzo/ui'  // component API
//   import { PageHeader, Sparkline, EmptyState } from '@hanzo/ui/product'           // product/app layer
//   import { RecordsView, registerField } from '@hanzo/ui/data'                     // metadata record layer
//   import { ModelSelector } from '@hanzo/ui/models'                                // unified model picker
//   import { cn, themes, colors } from '@hanzo/ui/core'                             // design core + tokens
//   import '@hanzo/ui/theme.css'                                                    // the self-contained identity
//
// Styling is theme tokens, never utility classes: `$background`, `$color12`,
// `$borderColor` resolve through the gui token config on every host. Touch
// targets meet the 44px floor via `hitSlop`, never via padding.
// Named, not `export *`.
//
// This module is a client boundary ('use client' above), and Next 16 refuses
// `export *` across one: "It's currently unsupported to use `export *` in a client
// boundary." Every app importing the root barrel failed to build on that one line.
//
// Naming them also restores tree-shaking, which `export *` defeats — a bundler
// cannot prove which members are unused through a star, so importing Button pulled
// the whole surface in.
//
// ./backends/gui declares these as explicit named blocks and this list mirrors it.
//
// It is maintained BY HAND — `scripts/gen-primitives.mjs` writes `src/primitives/`,
// not this file, so nothing regenerates it and nothing used to notice when the two
// drifted. Glass, Grid, Band and CardMedia were all exported by the backend and
// absent here, which means a consumer could not import them AT ALL: the component
// existed, the docs named it, and `import { Grid } from '@hanzo/ui'` was undefined.
// `src/__tests__/barrel.test.ts` now fails when the two disagree.
export {
  AspectRatio, Avatar, AvatarFallback, AvatarImage, Badge, Button, Card, CardAction,
  CardContent, CardDescription, CardFooter, CardHeader, CardMedia, CardTitle, Checkbox,
  Collapsible,
  CollapsibleContent, CollapsibleTrigger, Command, CommandDialog, CommandEmpty, CommandGroup,
  CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut, Dialog,
  DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay,
  DialogPortal, DialogTitle, DialogTrigger, DropdownMenu, DropdownMenuCheckboxItem,
  DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel,
  DropdownMenuPortal, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator,
  DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger,
  DropdownMenuTrigger, Em, Glass, Fill, H1, H2, H3, H4, H5, H6, Heading, Image, Input,
  Label, Popover, PopoverAnchor, PopoverClose,
  PopoverContent,
  PopoverTrigger, Progress, ResizableHandle, ResizablePanel, ResizablePanelGroup, ScrollArea,
  ScrollBar, Select, SelectContent, SelectGroup, SelectItem, SelectLabel,
  SelectScrollDownButton, SelectScrollUpButton, SelectSeparator, SelectTrigger, SelectValue,
  Paragraph, Screen, ScrollView, Band, Separator, SizableText, Slider, Spacer, Span, Spinner, Strong,
  Switch, Tabs, TabsContent,
  TabsList, TabsTrigger, Textarea,
  Toaster,
  Text, Tooltip, TooltipContent, TooltipProvider, TooltipTrigger, View, XStack, YStack,
  ZStack, toast,
  ApplyTypography, Link, LinkElement, MDXLink, VideoPlayer, YouTubeEmbed, useLink,
  Form, FormField, FormItem, FormLabel, FormControl, FormDescription, FormMessage, useFormField,
  Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext,
  Skeleton, MediaStack, NavItems, StepIndicator,
  Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader,
  SheetOverlay, SheetPortal, SheetTitle, SheetTrigger,
  Breadcrumb, BreadcrumbEllipsis, BreadcrumbItem, BreadcrumbLink, BreadcrumbList,
  BreadcrumbPage, BreadcrumbSeparator,
  InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot,
  NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink,
  NavigationMenuList, NavigationMenuTrigger, Drawer, DrawerContent, DrawerHandle, DrawerTrigger,
  Accordion, AccordionContent, AccordionItem, AccordionTrigger, AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogOverlay, AlertDialogPortal, AlertDialogTitle, AlertDialogTrigger, ContextMenu, ContextMenuCheckboxItem, ContextMenuContent, ContextMenuGroup, ContextMenuItem, ContextMenuLabel, ContextMenuPortal, ContextMenuRadioGroup, ContextMenuRadioItem, ContextMenuSeparator, ContextMenuShortcut, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuTrigger, HoverCard, HoverCardContent, HoverCardTrigger, RadioGroup, RadioGroupItem, ToggleGroup, ToggleGroupItem, } from './backends/gui'

export type {
  AspectRatioProps, BadgeProps, BadgeVariant, ButtonProps, ButtonSize, ButtonVariant,
  CommandFilter, CommandProps, DropdownMenuProps, InputProps, ResizableHandleProps, SpinnerProps,
  ResizablePanelGroupProps, ResizablePanelProps,
  AccordionContentProps, AccordionItemProps, AccordionProps, AccordionTriggerProps, AlertDialogContentProps, AlertDialogOverlayProps, AlertDialogProps, AlertDialogSectionProps, ContextMenuContentProps, ContextMenuItemProps, ContextMenuSubContentProps, HoverCardContentProps, HoverCardProps, HoverCardTriggerProps, RadioGroupItemProps, RadioGroupProps, ToggleGroupItemProps, ToggleGroupProps,
  ToggleGroupSize, ToggleGroupVariant,
  CarouselApi, CarouselOptions, CarouselProps, MediaStackProps,
  NavItemsProps, StepIndicatorProps, InputOTPProps, OTPSlot,
  DrawerProps, DrawerContentProps, SnapPoint, SheetContentProps, SheetSide,
} from './backends/gui'

// LAYOUT — the stacks and the type scale reach consumers through the component
// barrel above, which already names XStack/YStack/ZStack, the type scale
// (SizableText, Paragraph, Heading, H1-H6, Span, Strong, Em) and Image, Spacer,
// ScrollView, View and Text. This block adds only what that one lacks.
//
// It used to repeat all twenty, and TypeScript rejects a name exported twice from
// one module: `error TS2300: Duplicate identifier 'Em'` and nineteen more, so
// `tsc -p tsconfig.build.json` failed and @hanzo/ui could not build AT ALL. That
// took the whole cicd lane down with it — the test gate runs
// `pnpm --filter @hanzo/ui... build` first, so no test ever ran and ui.hanzo.ai
// could not ship.
//
// The concern the duplication came from is real and still holds: a name must be
// on the ROOT barrel to reach a consumer — 8.0.65 added these to the backend only
// and the dist still had no XStack, a green release that changed nothing. The fix
// for that is to name it once here, not twice.
export {
  Anchor,
  type GuiElement,
} from './backends/gui'

// The components ported onto the gui backend in the 8.27 line; the backend barrel
// names each module and this mirrors it, as the block above does.
export {
  Card3D,
  Card3DContent,
  Card3DDescription,
  Card3DFooter,
  Card3DHeader,
  Card3DTitle,
  Marquee3D,
  Marquee3DFloating,
  Marquee3DPreset,
  Pin3D,
  AdvancedChart,
  Alert,
  AlertDescription,
  AlertTitle,
  Android,
  AnimatedBeam,
  AnimatedCursor,
  AnimatedTestimonials,
  AnimatedTooltip,
  Announcement,
  AppleCardsCarousel,
  gradientPresets,
  AppleHelloEffect,
  Banner,
  Calendar,
  Choicebox,
  CodeBlock,
  CodeEditor,
  CodeTabs,
  ColorPicker,
  Combobox,
  ComboboxWithIcons,
  CompanyProfile,
  Comparison,
  CreditCard,
  MarketOverview,
  CryptoScreener,
  Cursor,
  DataTable,
  DataTableColumnHeader,
  DatePicker,
  Desktop,
  useDesktopSettings,
  useKeyboardShortcuts,
  useOverlayManager,
  useWindowManager,
  Spotlight,
  DesktopWindow,
  DesktopWindowControls,
  DialogStack,
  Dock,
  DockItem,
  DockSeparator,
  Dropzone,
  Editor,
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldTitle,
  Financials,
  ForexMarket,
  ForexScreener,
  Gantt,
  Glimpse,
  GlimpseContent,
  GlimpseDescription,
  GlimpseImage,
  GlimpseTitle,
  GlimpseTrigger,
  GridPattern,
  GridPatternPresets,
  ImageCrop,
  ImageZoom,
  InteractiveGridPattern,
  IPhone15Pro,
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemFooter,
  ItemGroup,
  ItemHeader,
  ItemMedia,
  ItemSeparator,
  ItemTitle,
  KanbanBoard,
  Kbd,
  KbdGroup,
  LimelightNav,
  List,
  ListItem,
  MacosDock,
  MacosDockItem,
  Magnetic,
  Marquee,
  MenuDock,
  Menubar,
  MenubarCheckboxItem,
  MenubarContent,
  MenubarGroup,
  MenubarItem,
  MenubarLabel,
  MenubarMenu,
  MenubarPortal,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarSeparator,
  MenubarShortcut,
  MenubarSub,
  MenubarSubContent,
  MenubarSubTrigger,
  MenubarTrigger,
  MessageDock,
  MiniCalendar,
  MinimalTiptap,
  MotionHighlight,
  NavigationBar,
  NewsTimeline,
  OrderEntry,
  OrdersHistory,
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
  Particles,
  ParticlesBackground,
  Pill,
  pillVariants,
  PinList,
  PixelImage,
  PositionsList,
  QRCode,
  encodeQr,
  RelativeTime,
  Safari,
  InlineCode,
  Snippet,
  StarsScrollingWheel,
  Status,
  StockMarket,
  StockScreener,
  SymbolInfo,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
  Tags,
  TechnicalAnalysis,
  Terminal,
  Ticker,
  Timeline,
  Toggle,
  MediaPlayer,
  type Card3DContentProps,
  type Card3DDescriptionProps,
  type Card3DFooterProps,
  type Card3DHeaderProps,
  type Card3DProps,
  type Card3DTitleProps,
  type Marquee3DDirection,
  type Marquee3DFloatingProps,
  type Marquee3DPerspective,
  type Marquee3DProps,
  type Marquee3DSize,
  type Marquee3DVariant,
  type Pin3DProps,
  type AdvancedChartInterval,
  type AdvancedChartProps,
  type AdvancedChartTheme,
  type AlertDescriptionProps,
  type AlertProps,
  type AlertTitleProps,
  type AlertVariant,
  type AndroidProps,
  type AndroidSize,
  type AnimatedBeamProps,
  type AnimatedCursorBlendMode,
  type AnimatedCursorProps,
  type AnimatedCursorShape,
  type AnimatedCursorPosition,
  type CursorState,
  type AnimatedTestimonialsProps,
  type Testimonial,
  type AnimatedTooltipProps,
  type AnnouncementProps,
  type AppleCardsCarouselProps,
  type CarouselCard,
  type AppleHelloEffectProps,
  type BannerProps,
  type BannerVariant,
  type CalendarMultipleProps,
  type CalendarProps,
  type CalendarRange,
  type CalendarRangeProps,
  type CalendarSingleProps,
  type ChoiceboxOption,
  type ChoiceboxProps,
  type CodeBlockDiff,
  type CodeBlockProps,
  type CodeBlockSize,
  type CodeBlockTheme,
  type CodeEditorProps,
  type CodeEditorTheme,
  type CodeEditorWordWrap,
  type CodeTabsProps,
  type CodeTabsTab,
  type ColorPickerProps,
  type ComboboxIconOption,
  type ComboboxOption,
  type ComboboxProps,
  type ComboboxWithIconsProps,
  type CompanyProfileProps,
  type CompanyProfileTheme,
  type ComparisonColumn,
  type ComparisonItem,
  type ComparisonProps,
  type CreditCardProps,
  type CreditCardVariant,
  type MarketOverviewPreset,
  type MarketOverviewProps,
  type MarketOverviewSymbol,
  type MarketOverviewTab,
  type MarketOverviewTheme,
  type CryptoScreenerColumn,
  type CryptoScreenerMarket,
  type CryptoScreenerProps,
  type CryptoScreenerTheme,
  type CursorPosition,
  type CursorProps,
  type DataTableColumnApi,
  type DataTableColumnDef,
  type DataTableColumnHeaderProps,
  type DataTableInstance,
  type DataTableProps,
  type DataTableRow,
  type DataTableSortDirection,
  type DatePickerPreset,
  type DatePickerProps,
  type DatePickerRangeProps,
  type DatePickerSingleProps,
  type ColorScheme,
  type DesktopProps,
  type DesktopSettings,
  type DesktopSettingsActions,
  type DesktopDockPosition,
  type KeyboardShortcut,
  type OverlayManager,
  type OverlayState,
  type WindowId,
  type WindowManager,
  type WindowState,
  type SpotlightItem,
  type SpotlightProps,
  type DesktopWindowControlsProps,
  type DesktopWindowProps,
  type DesktopWindowType,
  type DialogStackItem,
  type DialogStackProps,
  type DockItemProps,
  type DockPosition,
  type DockProps,
  type DockSeparatorProps,
  type DropzoneAccept,
  type DropzoneProps,
  type EditorCommand,
  type EditorProps,
  type EmptyContentProps,
  type EmptyDescriptionProps,
  type EmptyHeaderProps,
  type EmptyMediaProps,
  type EmptyMediaVariant,
  type EmptyProps,
  type EmptyTitleProps,
  type FieldContentProps,
  type FieldDescriptionProps,
  type FieldErrorIssue,
  type FieldErrorProps,
  type FieldGroupProps,
  type FieldLabelProps,
  type FieldLegendProps,
  type FieldLegendVariant,
  type FieldOrientation,
  type FieldProps,
  type FieldSeparatorProps,
  type FieldSetProps,
  type FieldTitleProps,
  type FinancialsDisplayMode,
  type FinancialsProps,
  type FinancialsTheme,
  type ForexMarketPreset,
  type ForexMarketProps,
  type ForexMarketSymbol,
  type ForexMarketTab,
  type ForexMarketTheme,
  type ForexScreenerColumn,
  type ForexScreenerMarket,
  type ForexScreenerProps,
  type ForexScreenerScreen,
  type ForexScreenerTheme,
  type GanttProps,
  type GanttTask,
  type GlimpseContentProps,
  type GlimpseDescriptionProps,
  type GlimpseImageProps,
  type GlimpseProps,
  type GlimpseTitleProps,
  type GlimpseTriggerProps,
  type GridPatternAnimation,
  type GridPatternFade,
  type GridPatternGap,
  type GridPatternGradient,
  type GridPatternMaxArea,
  type GridPatternOffset,
  type GridPatternProps,
  type GridPatternSize,
  type GridPatternVariant,
  type ImageCropProps,
  type ImageZoomProps,
  type InteractiveGridPatternProps,
  type IPhone15ProColor,
  type IPhone15ProProps,
  type IPhone15ProVariant,
  type ItemActionsProps,
  type ItemContentProps,
  type ItemDescriptionProps,
  type ItemFooterProps,
  type ItemGroupProps,
  type ItemHeaderProps,
  type ItemMediaProps,
  type ItemMediaVariant,
  type ItemProps,
  type ItemSeparatorProps,
  type ItemSize,
  type ItemTitleProps,
  type ItemVariant,
  type KanbanBoardData,
  type KanbanBoardProps,
  type KanbanCard,
  type KanbanColumn,
  type KanbanLabel,
  type KanbanPriority,
  type KbdGroupProps,
  type KbdProps,
  type LimelightNavItem,
  type LimelightNavProps,
  type LimelightNavVariant,
  type ListItemProps,
  type ListProps,
  type MacosDockItemProps,
  type MacosDockProps,
  type MagneticProps,
  type MarqueeProps,
  type MenuDockItem,
  type MenuDockOrientation,
  type MenuDockProps,
  type MenubarContentProps,
  type MenubarItemProps,
  type MenubarMenuProps,
  type MenubarProps,
  type MessageDockMessage,
  type MessageDockMessageType,
  type MessageDockPosition,
  type MessageDockProps,
  type MiniCalendarProps,
  type MinimalTiptapProps,
  type MotionHighlightProps,
  type NavigationBarLink,
  type NavigationBarOption,
  type NavigationBarPerson,
  type NavigationBarProps,
  type NavigationBarVariant,
  type NewsTimelineFeedMode,
  type NewsTimelineProps,
  type NewsTimelineTheme,
  type OrderEntryProps,
  type OrderKind,
  type OrderSide,
  type PlacedOrder,
  type Order,
  type OrdersHistoryOrderType,
  type OrdersHistoryProps,
  type OrdersHistorySide,
  type OrdersHistoryStatus,
  type PaginationContentProps,
  type PaginationEllipsisProps,
  type PaginationItemProps,
  type PaginationLinkProps,
  type PaginationNextProps,
  type PaginationPreviousProps,
  type PaginationProps,
  type ParticlesProps,
  type ParticlesBackgroundProps,
  type PillProps,
  type PillVariant,
  type PinListItem,
  type PinListProps,
  type PixelImageProps,
  type Position,
  type PositionsListProps,
  type QRCodeImageSettings,
  type QRCodeLevel,
  type QRCodeProps,
  type RelativeTimeFormat,
  type RelativeTimeProps,
  type SafariProps,
  type SafariToolbarItem,
  type InlineCodeProps,
  type SnippetProps,
  type SnippetSize,
  type SnippetTheme,
  type SnippetVariant,
  type StarsScrollingWheelOrientation,
  type StarsScrollingWheelProps,
  type StarsScrollingWheelSize,
  type StatusProps,
  type StatusVariant,
  type StockMarketPreset,
  type StockMarketProps,
  type StockMarketSymbol,
  type StockMarketTab,
  type StockMarketTheme,
  type StockScreenerColumn,
  type StockScreenerMarket,
  type StockScreenerProps,
  type StockScreenerScreen,
  type StockScreenerTheme,
  type SymbolInfoProps,
  type SymbolInfoTheme,
  type TableBodyProps,
  type TableCaptionProps,
  type TableCellProps,
  type TableFooterProps,
  type TableHeadProps,
  type TableHeaderProps,
  type TableProps,
  type TableRowProps,
  type Tag,
  type TagsProps,
  type TechnicalAnalysisDisplayMode,
  type TechnicalAnalysisInterval,
  type TechnicalAnalysisProps,
  type TechnicalAnalysisTheme,
  type TerminalCommand,
  type TerminalLineType,
  type TerminalProps,
  type TerminalTheme,
  type TickerDirection,
  type TickerProps,
  type TimelineItem,
  type TimelineOrientation,
  type TimelineProps,
  type TimelineStatus,
  type TimelineVariant,
  type ToggleProps,
  type ToggleSize,
  type ToggleVariant,
  type MediaPlayerProps,
  type MediaPlayerSize,
  type MediaSource,
  type MediaSubtitleTrack,
  type MenubarTriggerProps,
} from './backends/gui'

// `Hanzo` — the root, and the only thing an app mounts. It carries the gui
// config and the generated stylesheet, so `npm i @hanzo/ui` is the whole setup:
// no gui.config.ts, no CSS import, no generator script.
export { Hanzo, type HanzoProps } from './root'

// `cn` — the class-name composer, surfaced for convenience.
// The type goes with the function. `cn(...inputs: ClassValue[])` cannot be
// typed at a call site without it, so exporting one and not the other left
// every consumer reaching into a subpath for half of a pair.
export { Slot, type SlotProps } from './slot'
export {
  cn, capitalize, variants,
  type ClassValue, type Variants, type Choice, type VariantProps,
} from './core/cn'

// The design-token scale (colors, dark/light themes, radii, spacing, typography)
// lives on the `@hanzo/ui/core` / `@hanzo/ui/tokens` subpath — pure data, no
// runtime.

export { tw, type Parsed, type Props as TwProps } from './tw'
export { Box, type BoxProps } from './box'
export { sx } from './sx'
export { css } from './css'

export { buttonVariants, badgeVariants, navigationMenuTriggerStyle, fit } from './style'

// The config the components are styled against, for a host that lays out with
// @hanzo/gui stacks of its own.
export { config, type Conf } from './gui-config'
