packages:
  - "apps/*"
  - "pkg/*"
  - "pkgs/*"
  - "!**/test/**"
  - "!**/fixtures/**"
  - "!**/temp/**"
  - "!deprecated/**"

catalog:
  '@hanzo/appearance': 0.2.2
  '@hanzo/brand': 1.4.8
  '@hanzo/canvas': 0.2.3
  '@hanzo/cd': 0.1.2
  '@hanzo/commerce': 7.7.2
  '@hanzo/dashboard': 0.2.0
  '@hanzo/data': 1.2.4
  '@hanzo/design': 0.5.24
  '@hanzo/event': 0.3.37
  '@hanzo/events': 0.2.2
  '@hanzo/font': 1.9.2
  '@hanzo/gui': 8.3.0
  '@hanzo/logo': 1.0.26
  '@hanzo/observe': 0.1.8
  '@hanzo/products': 0.2.6
  '@hanzo/ui': 8.25.0
  '@hanzo/usage': 0.1.7
