// GENERATED by scripts/gen-primitives.mjs — do not edit. Per-member entrypoint
// for hosts that modularize `@hanzo/ui` imports. Source of truth:
// src/backends/shadcn/index.ts. Re-run: node scripts/gen-primitives.mjs
export { SelectLabel } from '../backends/shadcn'
