// GENERATED by scripts/gen-primitives.mjs — do not edit. Per-member entrypoint
// for hosts that modularize `@hanzo/ui` imports. Source of truth:
// src/backends/gui/index.ts. Re-run: node scripts/gen-primitives.mjs
export { SelectItem } from '../backends/gui/select'
