// Generated by scripts/sync.mjs from https://api.hanzo.ai/v1/commerce/catalog. Do not edit.
//
// hanzoai/commerce owns this taxonomy — it is the catalog admin.hanzo.ai edits
// and the API every surface reads. Run `pnpm sync` to carry a change down.

/** Every product category, in the catalog's display order. */
export const CATEGORIES = [
  "AI",
  "Compute",
  "Data",
  "Network",
  "Security",
  "Dev",
  "Platform",
  "Observe",
  "Web3",
  "Apps",
] as const

/** The categories each brand's console admits. `null` = all of them. */
export const BRAND_SCOPE = {
  hanzo: null,
  lux: ["Web3", "Network", "Security", "Dev"],
  zoo: ["Web3", "Network", "Security", "Dev"],
  pars: ["Web3", "Network", "Security", "Dev"],
} as const
