// Write dist/styles.css — every rule @hanzo/ui's own components need, extracted
// at OUR publish time instead of at each app's.
//
// @hanzo/gui compiles a style prop to an atomic class the first time something
// RENDERS it, so the sheet does not exist until a render has happened. Every app
// therefore had to run a generator of its own and import the output. hanzo.app
// did not, and shipped 103 `_bg-` classes and 26 `_dsp-` classes against a
// stylesheet containing zero of either — every gui-styled element unstyled in
// production, with a green build for the whole life of the bug.
//
// The render happens here instead. src/gallery.tsx is the list of what to render
// and it is the same list the unit test mounts and the consumer test asserts
// against, so a component cannot be styled by one and missed by another.
//
// `config.getCSS()` returns gui's design-system rules, the token and font custom
// properties, the theme rule sets, and `getAllRules()` — the atomic rules this
// process accumulated. Accumulation happens during `getSplitStyles`, which is
// why a plain `renderToStaticMarkup` is enough and no DOM is involved.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { StyleSheet } from 'react-native-web'
import { createServer } from 'vite'

import { alias } from './alias.mjs'

const UI = dirname(dirname(fileURLToPath(import.meta.url)))

// Rendering must not be told the CSS was already emitted — that flag makes
// getCSS() and getAllRules() return empty and there is nothing to write.
delete process.env.GUI_DID_OUTPUT_CSS

const server = await createServer({
  root: UI,
  configFile: false,
  logLevel: 'error',
  css: { postcss: { plugins: [] } },
  resolve: { alias },
  // The aliases only reach source vite transforms, and the icon set's
  // `react-native-svg` import is inside @hanzogui — so gui has to be inlined for
  // the stub to apply. react-native-web stays external: it is Node-loadable, and
  // inlining it drags in CommonJS (`@react-native/normalize-color`) that vite's
  // SSR runner evaluates as ESM and dies on.
  ssr: { noExternal: [/@hanzogui\//, /@hanzo\/gui/] },
})



try {
  const { GuiProvider } = await server.ssrLoadModule('@hanzo/gui')
  const { config, css: guiCSS } = await server.ssrLoadModule(join(UI, 'src/gui-config.ts'))
  const { Gallery } = await server.ssrLoadModule(join(UI, 'src/gallery.tsx'))

  // Both themes: a theme is a set of custom-property values, but the styles that
  // READ them are per-theme classes, and a component only renders the ones its
  // theme resolves. Rendering dark alone leaves the light sheet incomplete.
  const markup = {}
  for (const theme of ['dark', 'light'])
    markup[theme] = renderToStaticMarkup(
      createElement(GuiProvider, { config, defaultTheme: theme }, createElement(Gallery)),
    )

  // The un-shadowing lives WITH the config (src/gui-config.ts `css()`), because
  // every app runs a generator of its own and a fix inside this one script
  // reaches only this package's sheet.
  const gui = guiCSS()
  // dist/theme.css, not src: the token layer is @hanzo/design's, composed in
  // by scripts/compose-theme.mjs. Reading src here would ship a stylesheet whose
  // components reference tokens the sheet never declares.
  const tokens = readFileSync(join(UI, 'dist/theme.css'), 'utf8')
  const motion = readFileSync(join(UI, 'src/styles/motion.css'), 'utf8')

  // `--hanzo-ui-styles` is what <Hanzo> looks up to tell a consumer, in
  // development, that this file never reached the document.
  // react-native-web keeps its own sheet, and gui renders through it — every
  // ScrollView here is an rnw ScrollView, so `overflow-y: auto` is an rnw rule.
  // In a browser rnw appends that sheet itself on import, which is why an app
  // works and this file could omit it for so long. Nothing appends it during a
  // server render, so the sheet we SHIP omitted it too: 20 rnw classes appeared
  // in the gallery's markup with no rule anywhere, `dist/gallery.html` rendered
  // every one of those components as unstyled block-level HTML, and
  // `responsive.mjs` measured that page. It goes first, being the base layer
  // that gui's atomic classes then override.
  const rnw = StyleSheet.getSheet().textContent
  if (!rnw.includes('css-view-')) throw new Error('react-native-web emitted no base rules')

  const css = [
    '/* @hanzo/ui — generated by scripts/gen-css.mjs. Do not edit. */',
    ':root { --hanzo-ui-styles: 1; }',
    tokens,
    rnw,
    motion,
    gui,
  ].join('\n')

  mkdirSync(join(UI, 'dist'), { recursive: true })
  writeFileSync(join(UI, 'dist/styles.css'), css)

  const atomic = (gui.match(/\._[\w-]+/g) ?? []).length
  console.log(
    `dist/styles.css — ${css.length.toLocaleString()} bytes, ${atomic.toLocaleString()} atomic selectors`,
  )

  // The same render, kept. Every component this package has, in the markup it
  // actually produces, against the sheet just extracted from it — so what a
  // reader looks at and what a consumer installs cannot disagree. gui stamps the
  // theme on the body, which is why the class is here and not on a wrapper.
  // The theme class goes on <html>, because that is where gui's own generated
  // CSS scopes the palette: every colour token is declared under `:root.t_dark`.
  // On <body> the selector cannot match, so `var(--red9)` and every sibling
  // resolve to nothing, each declaration reading them is dropped as invalid, and
  // the page renders as bare high-contrast outlines — variants indistinguishable,
  // spacing collapsed. It looks like a design, which is why it needs saying.
  const page = [
    '<!doctype html><html lang="en" class="t_dark"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    `<title>@hanzo/ui ${JSON.parse(readFileSync(join(UI, 'package.json'), 'utf8')).version}</title>`,
    `<style>${css}</style>`,
    '</head><body>',
    markup.dark,
    '</body></html>',
  ].join('')
  writeFileSync(join(UI, 'dist/gallery.html'), page)
  console.log(`dist/gallery.html — ${page.length.toLocaleString()} bytes`)
} finally {
  await server.close()
}

// Vite's module runner leaves handles open that `close()` does not reap, and a
// build step that writes its output and then never exits hangs `prepack`, which
// hangs `pnpm pack`, which hangs `pnpm publish`. The work is done; leave.
process.exit(0)
