// gen-css.mjs — the ONE TS→CSS bridge for @hanzo/tokens.
//
// The token VALUES live in src/theme.ts (dark, light, scale). This script reads
// them and emits the CSS custom-property bundle that non-React surfaces embed:
//
//   dist/colors.css  — the colour tokens only (:root dark + .light). This is the
//                      contract @hanzo/design's tokens/colors.css republishes,
//                      byte-for-byte in values, so its existing consumers (the
//                      git/ci/cd surfaces, and any app linking styles.css) keep
//                      working with one edit here instead of three hand-copies.
//   dist/tokens.css  — the full bundle: the same colours PLUS radius, type and
//                      spacing. This is the `@hanzo/tokens/css` export and what
//                      @hanzo/brand re-emits for Go surfaces.
//
// Runs after tsup, importing the built ./dist/theme.mjs — so the numbers the CSS
// carries are exactly the numbers the TypeScript exports; they cannot drift.
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { dark, light, scale } from '../dist/theme.mjs'

const dist = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist')

const decl = (v) => `  --${v.name}:${v.value};${v.comment ? ` /* ${v.comment} */` : ''}`
const banner = (title) => `\n  /* ——— ${title} ——— */`
const block = (sections) => sections.map((s) => `${banner(s.title)}\n${s.vars.map(decl).join('\n')}`).join('\n')

/** :root{ color-scheme:dark; …dark… } .light{ color-scheme:light; …light… } */
function sheet(header, rootSections, lightSections) {
  return (
    `${header}\n\n` +
    `:root{\n  color-scheme:dark;\n${block(rootSections)}\n}\n\n` +
    `.light{\n  color-scheme:light;\n${block(lightSections)}\n}\n`
  )
}

const GENERATED =
  '/* AUTO-GENERATED by @hanzo/tokens scripts/gen-css.mjs from src/theme.ts — DO NOT EDIT.\n' +
  ' * Edit the token in @hanzo/tokens src/theme.ts and re-run `pnpm --filter @hanzo/tokens gen-css`. */'

const colorsCss = sheet(
  `${GENERATED}\n/* Hanzo colour tokens — monochrome, dark-default. One hue, an opacity ladder. */`,
  dark,
  light,
)
writeFileSync(join(dist, 'colors.css'), colorsCss)

const tokensCss = sheet(
  `${GENERATED}\n/* Hanzo design tokens — colour + radius + type + spacing. The full bundle. */`,
  [...dark, ...scale],
  light,
)
writeFileSync(join(dist, 'tokens.css'), tokensCss)

const count = (s) => s.reduce((n, g) => n + g.vars.length, 0)
console.log(
  `gen-css: wrote dist/colors.css (${count(dark)} dark + ${count(light)} light) ` +
    `and dist/tokens.css (+${count(scale)} scale)`,
)
