// Generated by scripts/sync.mjs from https://api.hanzo.ai/v1/commerce/catalog. Do not edit.
//
// hanzoai/commerce owns this taxonomy — it is the catalog admin.hanzo.ai edits
// and the API every surface reads. Run `pnpm sync` to carry a change down.

/** Every product category, in the catalog's display order. */
export const CATEGORIES = [
  "AI",
  "Compute",
  "Data",
  "Network",
  "Security",
  "Dev",
  "Infrastructure",
  "Observe",
  "Web3",
  "Apps",
] as const

/** The categories each brand's console admits. `null` = all of them. */
export const BRAND_SCOPE = {
  hanzo: null,
  lux: ["Web3", "Network", "Security", "Dev"],
  zoo: ["Web3", "Network", "Security", "Dev"],
  pars: ["Web3", "Network", "Security", "Dev"],
} as const

/**
 * The accent each category reads as — a swatch key, resolved to css by
 * `swatchHex`, exactly like a product's `brandColor`.
 *
 * Served by the catalog, not chosen per surface: a category drawn teal in the
 * console and indigo on the site is two different categories to anyone looking
 * at both, which is what happened while this mapping lived in two files and was
 * owned by neither.
 */
export const COLORS = {
  "AI": "violet",
  "Compute": "blue",
  "Data": "cyan",
  "Network": "sky",
  "Security": "red",
  "Dev": "indigo",
  "Infrastructure": "teal",
  "Observe": "green",
  "Web3": "amber",
  "Apps": "pink",
} as const
